spring:
  application:
    name: myproductbak
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sell
    username: root
    password: root
  #rabbitmq:
   # host: localhost
    #port: 5672
    #username: guest
    #password: guest
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mygroup
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
jpa:
  show-sql: true
env: test